# Generated by Hermes 2026-05-27 — see top-of-file comment.
# NanoClaw AWS Infrastructure — Secrets Manager

# IMPORTANT: This Terraform file generates the **default / placeholder** payload
# for the `nanoclaw/app-config` secret. The keys here must match what
# `src/cloud/secrets/index.ts::parseSecretPayload` expects (lower_snake_case).
# Mismatched keys silently fall back to defaults at runtime, so any drift
# between this file and the secret parser shows up as production bugs.
#
# Surface-specific model split:
#   - llm_model_id          -> orchestrator + high-reasoning calls (Opus by default)
#   - llm_subagent_model_id -> per-user worker container (Sonnet by default)
#
# After deploy, update via the AWS Console or:
#   aws secretsmanager update-secret `
#     --region ap-southeast-1 `
#     --secret-id nanoclaw/app-config `
#     --secret-string file://payload.json

resource "aws_secretsmanager_secret" "app_config" {
  name        = "${var.project_name}/app-config"
  description = "NanoClaw application configuration secrets"

  tags = {
    Name = "${var.project_name}-app-config"
  }
}

# Default secret payload. Keys are lower_snake_case to match the TS parser.
resource "aws_secretsmanager_secret_version" "app_config" {
  secret_id = aws_secretsmanager_secret.app_config.id

  secret_string = jsonencode({
    # WhatsApp (Baileys) — no secret needed, session-based auth on S3
    WHATSAPP_SESSION_S3_PREFIX = "sessions/"

    # Redis connection (auto-populated from Terraform)
    redis_host = local.redis_host
    redis_port = local.redis_port
    redis_tls  = local.redis_tls

    # OpenSearch endpoint (auto-populated)
    opensearch_endpoint   = aws_opensearchserverless_collection.documents.collection_endpoint
    opensearch_index_name = "documents"

    # S3 bucket (auto-populated)
    s3_data_bucket = aws_s3_bucket.data.id

    # DynamoDB table names (auto-populated)
    dynamodb_chat_messages_table    = aws_dynamodb_table.chat_messages.name
    dynamodb_webhook_tokens_table   = aws_dynamodb_table.webhook_tokens.name
    dynamodb_user_preferences_table = aws_dynamodb_table.user_preferences.name
    dynamodb_system_errors_table    = aws_dynamodb_table.system_errors.name

    # Bedrock model IDs.
    #   llm_model_id          : orchestrator-side default (Opus, high reasoning)
    #   llm_subagent_model_id : container-side default   (Sonnet, high volume)
    llm_model_id               = "anthropic.claude-opus-4-7"
    llm_subagent_model_id      = "anthropic.claude-sonnet-4-6"
    llm_region                 = var.aws_region
    BEDROCK_EMBEDDING_MODEL_ID = "amazon.titan-embed-text-v2:0"

    # ECR refs (consumed by container-manager when spawning sub-agents)
    ecr_registry_url = "${data.aws_caller_identity.current.account_id}.dkr.ecr.${var.aws_region}.amazonaws.com"
    ecr_agent_image  = "${var.project_name}/agent:latest"

    # Application config
    RATE_LIMIT_PER_USER_PER_MIN = "20"
    RATE_LIMIT_GLOBAL_PER_HOUR  = "200"
    NOTIFICATION_TIMEZONE       = "Asia/Singapore"
  })

  # The live secret is the source of truth at runtime. Terraform sets the
  # initial value; subsequent edits via the Console or CI must not be clobbered
  # on every `terraform apply`.
  lifecycle {
    ignore_changes = [secret_string]
  }
}

# (caller identity declared in versions.tf)
